apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moc-nfs-democratic-csi
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  project: default
  source:
    repoURL: https://github.com/larsks/moc-nfs-democratic-csi.git
    targetRevision: master
    path: overlays/oai-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
