apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oai-demo-webserver
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  project: default
  source:
    repoURL: https://github.com/larsks/oai-demo-webserver.git
    targetRevision: master
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
